### ISSUE TITLE
disable send_anonymous_usage_stats for CI runs?

### ISSUE THREAD

**Issue by dataders** [microsoft/dbt-synapse#34]
@jtcohen6 is this something we need to do for this adapter and `dbt-sqlserver`? or is it already taken care of by `dbt-adapter-tests`?

**Comment by jtcohen6** [comment]
Taken care of [in dbt-adapter-tests](https://github.com/fishtown-analytics/dbt-adapter-tests/blob/104a63075f06993f06743bf4d29b84737f479202/pytest_dbt_adapter/spec_file.py#L566)
