### ISSUE TITLE
Could not load dbt_project.yml

### ISSUE THREAD

**Issue by jbertscher** [microsoft/dbt-synapse#51]
Hi, I've been struggling to get dbt-synapse set up for a while but can't crack it.

When I run `dbt debug`, it fails with:

```
Running with dbt=0.19.1
dbt version: 0.19.1
python version: 3.9.5
python path: .../bin/python
os info: macOS-11.2.3-x86_64-i386-64bit
Using profiles.yml file at .../.dbt/profiles.yml
Using dbt_project.yml file at .../dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [ERROR invalid]

Project loading failed for the following reason:
Runtime Error
  Invalid config version: 1, expected 2

Error encountered in .../dbt_project.yml

Required dependencies:
 - git [OK found]

Connection:
  server: ...
  database: ...
  schema: ...
  port: 1433
  UID: ...
  client_id: None
  authentication: sql
  encrypt: False
  trust_cert: False
  Connection test: OK connection ok

Could not load dbt_project.yml
```

**Comment by dataders** [comment]
You're almost there! I think it's saying that in your `dbt_project.yml` file, you need have `config-version: 2` like below. This came about as part of [dbt version `0.17.0`](https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0/).

```yml
name: my_project
version: 1.0.0

config-version: 2

models:
  ...
```

**Comment by jbertscher** [comment]
Amazing - that worked! Thanks a lot!

**Comment by dataders** [comment]
@jbertscher no prob. reach out here (or in the [dbt Slack](https://community.getdbt.com/)'s #db-synapse channel) if you come across other hiccups. closing this issue now.
