### ISSUE TITLE
Azure Synapse serverless pool

### ISSUE THREAD

**Issue by AndresNamm** [microsoft/dbt-synapse#58]
Do you have a plan to implement a feature that allows to access Azure Synapse with the serverless pool as well? Currently, it seems this is not possible because the Azure Synapse serverless pool is based on external tables.

**Comment by dataders** [comment]
great question! actually [dbt-labs/dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables) supports Azure Synapse. So you can make external tables using that package ([example](https://github.com/dbt-labs/dbt-external-tables/blob/master/sample_sources/synapse.yml)), then, as long as your whole make all your dbt models views, it should work!

Our team uses this pattern extensively.

I'm going to close this issue, but please reply back if you have any questions!
