### ISSUE TITLE
profiles.yml file [ERROR INVALID]

### ISSUE THREAD

**Issue by hsanjaysharma93** [microsoft/dbt-synapse#60]
I am facing the below issue, can anyone help??
I am dockerizing the dbt and below is docker file
FROM python:3.8.5
# Update and install system packages
RUN apt-get update -y && \
  apt-get install --no-install-recommends -y -q \
  git libpq-dev python-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
# Install DBT
RUN pip install -U pip
RUN pip install dbt==0.19.1
COPY /root/.dbt
WORKDIR /root/.dbt
------------
profile name is matching in both profiles.yml and dbt_project.yml, and profiles.yml is good
and in dbt_project.yml i am using version:1.0.0 and config-version:2
when I am running in my  local with the  image build from docker file using command, everyrhing is working fine
docker run -v github/profiles.yml/:/root/.dbt/profiles.yml dbt debug --profiles-dir /root/.dbt
github/profiles.yml( its the path of new profiles.yml mounting at run time in docker run)
but when i am running in codefresh as pipeline with same command
docker run -v github/profiles.yml/:/root/.dbt/profiles.yml dbt debug --profiles-dir /root/.dbt
I am getting the below error
using profiles.yml file at /root/.dbt/profiles.yml
using dbt_project.yml file at /root/.dbt/profiles.yml
configration :
     profiles.yml file [ERROR INVALID]
     dbt_project.yml [ok found and valid]
profile loading failed for following reason:
Runtime error
   could not find profile named ‘cdm’
can you help me why i am facing the issue with profiles.yml in codefresh, whereas in local its working fine (

**Comment by dataders** [comment]
@hsanjaysharma93 sounds frustrating! before I can help, can you please:

1. properly format your docker image code snippet using triple backtick (`) like this?
    <img width="157" alt="image" src="https://user-images.githubusercontent.com/8158673/130486020-0ac279fc-d772-4a79-9219-ef9d414d51f8.png">
2. can you share what your `profiles.yml` looks like (with credentials removed)?
2. can you run the container in interactive mode and run `dbt debug` successfully?

**Comment by dataders** [comment]
closing -- please open again if you have more information to share
